# Generated by Django 3.0.3 on 2020-02-14 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='use_period',
        ),
    ]
