# Generated by Django 3.0.3 on 2020-02-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Communi_User',
        ),
        migrations.RemoveField(
            model_name='item',
            name='use_period',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
