# Generated by Django 3.0.3 on 2020-02-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20200220_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default='something', max_length=50),
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
    ]
