# Generated by Django 3.0.3 on 2020-02-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20200218_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, height_field=200, upload_to='uploads/%Y/%m/%d/', width_field=200),
        ),
    ]
