# Generated by Django 3.0.3 on 2020-02-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_itemavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemavailability',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('requested', 'requested'), ('borrowed', 'borrowed')], default='available', max_length=20),
        ),
    ]
