# Generated by Django 3.0.3 on 2020-02-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_itemavailability_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemavailability',
            old_name='user',
            new_name='requesterS',
        ),
    ]
