# Generated by Django 3.0.3 on 2020-02-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_auto_20200225_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemavailability',
            old_name='requesterS',
            new_name='requester',
        ),
    ]
